### ISSUE TITLE
Driver Level Code integration

### ISSUE THREAD

**Issue by eden-desta** [micro-ROS/zephyr_apps#15]
Hello!
There isnt a lot of clarity how to include the driver configuration and software. Where do I place code for instance that I have generated from the Cube.

**Comment by ralph-lange** [comment]
Hello @edesta-be!
Thank you for pointing to this issue. Due to vacation, it will take a few days before your question can be fully answered. In the meanwhile, you may have a look at the FreeRTOS version, which includes some Cube-generated code (e.g., at https://github.com/micro-ROS/freertos_apps/blob/foxy/microros_olimex_e407_extensions/Src/freertos.c).

**Comment by pablogs9** [comment]
Hello @edesta-be, sorry for the delay.

Are you referring to the Zephyr code or FreeRTOS (STM32CubeMX generated) code?

**Comment by eden-desta** [comment]
@pablogs9 no problem!
My hope is to be able to use the initialised cube mx driver code (aka, spi, i2c, can etc) with the existing system.
And I am referring specifically to Zephyr. How do i integrate your system to include the driver code. 
Similar to the FreeRTOS integration.

Thank you!

**Comment by pablogs9** [comment]
Well, I'm not sure that generated code from CubeMX code is been used in the Zephyr environment. 

You have an example of an out of the tree driver implementation in Zephyr in this [demo app](https://github.com/micro-ROS/zephyr_apps/tree/foxy/apps/vl53l1x_tof_sensor).

Can you detail more specifically your use case?
- Which board are you targeting?
- Which RTOS are you going to use?
- Which bus (SPI, I2C...) and which peripheral are you using?

Thanks

**Comment by eden-desta** [comment]
Board Targeting is : nucleo_h743zi
RTOS: Zephyr
Peripheral: CAN

So to explain a little more. I have generated the peripheral using CubeMX. 
How do i access it in a zephyr app? How can i send something specific to the tx pin of the can i initialised and how can i pull in the data from the rx pin. 
So for the example any work displaying communication to the pins on a STM32 board would be amazing. 
I just do not understand how to cross over the zephyr apps to the CubeMX generated code. 

I am trying to access a peripheral through an app. Those low level pins. 

Thank you

**Comment by pablogs9** [comment]
Hello @edesta-be, thanks for the response.

One more thing, your intention is to use:
- micro-ROS over CAN 
- or, use some CAN peripheral and use micro-ROS with a UART (or net) transport?

**Comment by eden-desta** [comment]
Hi @pablogs9 

My intention is to use some CAN peripheral and use micro-ROS with an ethernet transport. 

Thank you!

**Comment by pablogs9** [comment]
Hello again @edesta-be, I think that it would be more useful to ask in the Zephyr repos about integration of new drivers support for some of their supported board.

We at micro-ROS are trying to keep our build system up-to-date with their newest version so if you find a solution using Zephyr RTOS for your use case, it should be compatible with micro-ROS.

Regarding this board, we are providing community (@CLansdaleBEC) support in this PR: https://github.com/micro-ROS/micro_ros_setup/pull/182. I hope that when this PR is merged you can use micro-ROS with your board with ethernet and serial transports (always if Zephyr have support for these peripherals in this board).

Sorry for not being so helpful with the CAN driver issue. I'm going to close this issue since it is not directly related to micro-ROS, but don't hesitate to open a new one if you have any problem with the @CLansdaleBEC port to the nucleo_h743zi board.

**Comment by eden-desta** [comment]
I guess you might have misunderstood my problem @pablogs9 The problem isnt integrating with Zephyr it is integrating with micro-ROS. What I was hoping for was guidance in calling these peripherals in a micro-ROS environment.  So i dont really have a CAN driver issue, i just want to use CAN (but I dont know how to access it on the micro-ROS side when I am writing applications similar to ping pong etc. Thats where i was hoping you could assist. 

And though @CLansdaleBEC port to the nucleo_h743 will be very useful, it is not answering the question of including the driver level extensions to your existing system. 
For example as @ralph-lange previously mentioned, the freeRTOS version of your apps has an example of driver code (generated from CUBE) integration. That's what I was hoping to see, either a set of steps to integrate the code or an example in a similar fashion. 

Thank you,
Eden

**Comment by pablogs9** [comment]
Using a peripheral driver inside a micro-ROS application does not involve any micro-ROS specific coding. For example [here](https://github.com/micro-ROS/zephyr_apps/blob/foxy/apps/sensors_publisher/src/main.c) you can see an example of how a micro ROS code running in Zephyr publish the data from an I2C ToF sensor in a ST B-L475E-IOT01A board.

In [this other example](https://github.com/micro-ROS/zephyr_apps/tree/foxy/apps/vl53l1x_tof_sensor), we are including a external driver for a sensor not supported by Zephyr. But this is not a micro-ROS procedure, it is Zephyr specific, you can find more here: https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/application_development/out_of_tree_driver

As you can see we use the Zephyr driver API and then we publish the data. Driver integration is done in the Zephyr side.

Can you provide us some steps of your workflow so we can reproduce the problem here?

**Comment by eden-desta** [comment]
Hi @pablogs9 I think i finally see what you are saying. I had to go through the firmware generated folder. You are absolutely correct it is on the zephyr end, thank you so much for your time!

Sincerely, 
Eden

**Comment by pablogs9** [comment]
You are welcome, please give us feedback about your micro-ROS experience if you think that you can contribute or improve something!

Thanks!!
