### ISSUE TITLE
What is the procedure for adding my own Zephyr app?

### ISSUE THREAD

**Issue by CLansdaleBEC** [micro-ROS/zephyr_apps#16]
Hello! I have zephyr and microROS working with the example apps, and now I would like to add my own custom application. 

I see that create_firmware_ws.sh imports the [board.repos](https://github.com/micro-ROS/micro_ros_setup/blob/foxy/config/zephyr/generic/board.repos) file, which then pulls the zephyr_apps repo. 

Is the best way to add my own application to replace that url with my own zephyr_apps repo? The issue with this approach is I would have to fork micro_ros_setup to edit create_firmware_ws.sh, which I would prefer not to in order to stay up to date.

**Comment by MS71** [comment]
Hi,
I am thinking about the same for ESP32.
In this case, replacing the app is not enough. Because the main function including some project configuration (sdkconfig) is located in the so called extension.
My wish would be a possibility to overwrite the app path and extension path by a pre defined environment variable.

Maik

**Comment by pablogs9** [comment]
Hello @CLansdaleBEC and @MS71, our way of creating a new app is just adding a new folder inside `firmware/zephyr_apps/apps` and adding the required files as explained [here](https://micro-ros.github.io/docs/tutorials/core/first_application_rtos/zephyr/). You can take any of the other folders as an example.

I understand that if you want to have your own custom micro-ROS apps repo it would be fine to have an environment variable pointing to the place where the apps are located. If you see the build script for Zephyr and micro-ROS you can see that we are [invoking west](https://github.com/micro-ROS/micro_ros_setup/blob/8c5eb51b27dedd4797239864b4d886ae6f0b28a4/config/zephyr/generic/build.sh#L65) in order to build the app, and this command uses `UROS_APP_FOLDER` environment variable. 

So, what do you think about conditionally setting `UROS_APP_FOLDER` in order to:
-  set it to the default location in the case that you have not provided an app location (let say something like `UROS_CUSTOM_APP_FOLDER`) 
- or, set it to `UROS_CUSTOM_APP_FOLDER` if you have provided it

Please give feedback about this and I will make the required changes.

By the way @MS71, we have not tested ESP32 with micro-ROS + Zephyr. It would be great to hear about your work in this way and if everything works as expected, creating a Pull Request contribution for integrating this support in the micro-ROS build system.

**Comment by CLansdaleBEC** [comment]
Yes I think a ```UROS_CUSTOM_APP_FOLDER``` optional argument makes a lot of sense. In my case I would like to separate my custom application from the firmware directory to separate it from the build process

**Comment by MS71** [comment]
Hi,
think using the UROS_CUSTOM_APP_FOLDER env variable approach is fine.

For the ESP32 use case, there are some important files (e.g. sdkconfig or partitions.csv) within the extension folder.
I would propose using the same approach for the extension folder too.

* defining UROS_CUSTOM_APP_FOLDER will allow an external APP folder.

* defining UROS_CUSTOM_EXT_FOLDER will allow an external EXT folder without any need for a APP folder. In this case "ros2 run micro_ros_setup configure_firmware.sh" is accepted without any or a dummy app argument.

I am not using ESP32 with Zephyr. I just have the same setup issue as reported by CLansdaleBEC.

**Comment by jamoralp** [comment]
Regarding the external app folder, I would keep the same approach used with our provided application set, that is, setting `UROS_CUSTOM_APP_FOLDER` to a path containing all the defined applications by the user, and then allowing, during `micro_ros_setup`'s configuration step, to choose which application you want to compile, from the available application list. This way, we keep the same command structure used for the built-in application set case. I would suggest making the the necessary changes to https://github.com/micro-ROS/micro_ros_setup/pull/183 to adopt this behaviour.

**Comment by pablogs9** [comment]
Agreed with @jamoralp.

@MS71 @CLansdaleBEC, please check and test if possible this PR: https://github.com/micro-ROS/micro_ros_setup/pull/183.

Don't hesitate to include any change you require to  `feature/custom_app_folder` branch.

@MS71 I'm not sure about having understood your proposal of `UROS_CUSTOM_EXT_FOLDER`, could you please propose the desired changes to this `feature/custom_app_folder` branch?
